#!/usr/bin/env bash
# Install and configure Nginx to display custom 404 error page

apt-get update
apt-get upgrade -y
apt-get install -y nginx
mkdir /etc/nginx/html -p
touch /etc/nginx/html/404.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
printf %s "server {
    listen  80 default_server;
    listen  [::]:80 default_server;
    root    /etc/nginx/html;
    index   index.html;
    location /redirect_me {
        return 301 http://jobabyyy.tech;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
