#!/usr/bin/env bash
# page not found 404

# Install nginx
sudo apt update
sudo apt install nginx -y

# Configure custom 404 page
echo "<html><body><h1>Ceci n'est pas une page</h1></body></html>" | sudo tee /var/www/html/404.html

# Configure the nginx default site to use the custom 404 page
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
        error_page 404 /404.html;
        location = /404.html {
            internal;
        }
    }
}
EOF'

# Restart nginx to apply the configuration changes
sudo service nginx restart
