#!/usr/bin/env bash
# inquire info abt files and check status

file=./school

if test -e "$file"; then 
	echo "school file exists"

	if [ -s "$file" ]; then
		echo "school file is not empty"
	
	else
		echo "school file is empty"
	
	fi
	
	if [ -f "$file" ]; then
		echo "school is a regular file"
	else "true"
	fi


else
	
	echo "school file does not exist"
fi
