#!/usr/bin/env bash
# inquire info abt files and check status

file=./School

if [ -e "$file" ]; then
	echo "$file file exists"

	if [ -s "$file" ]; then
		echo "$file file is not empty"
	
	else
		echo "$file file is empty"
	
	fi
	
	if [ -f "$file" ]; then
		echo "$file is a regular file"
	else "true"
	fi


else
	
	echo "$file file does not exist"
fi
