#!/usr/bin/env bash

# Define variables
KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"

# Generate the RSA key pair with given specifications
ssh-keygen -t rsa -b $KEY_BITS -f $KEY_NAME -N $PASSPHRASE

# Output success message
echo "RSA key pair generated successfully."
